Repository jsdrever/smart-vote, pull requests merged in 2023-05, with the labels that each got.

#11 Main container tweaks
  .gitignore
  client/public/index.html
  client/src/components/MainContainer.js
Labels: documentation, enhancement

#18 Jv/styling update for homepage and notfound
  README.md
  client/public/images/pin.jpg
  client/public/images/shirt.jpg
  client/public/images/thumb-1920-554598senate.jpg
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/Header.js
  client/src/components/MainContainer.js
  client/src/components/Navbar.js
  client/src/components/pages/Home.js
  client/src/components/pages/NotFound.js
Labels: documentation, enhancement

#22 made senators page dynammic but w/o api yet
  client/src/components/Navbar.js
  client/src/components/pages/Senators.js
  client/src/utils/API.js
Labels: documentation, enhancement

#25 footer update
  client/src/components/ContactForm.js
  client/src/components/Footer.js
  client/src/components/pages/Home.js
Labels: documentation, enhancement

#32 Jv/making bills page dynammic
  client/src/components/pages/Senators.js
Labels: bug, documentation, enhancement

#38 Jv/dotenv addition
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/pages/Bills.js
  client/src/components/pages/Senators.js
  client/src/utils/API.js
  package-lock.json
Labels: documentation, enhancement

#41 dotenv reapplication
  client/package-lock.json
  client/src/components/pages/Bills.js
  client/src/components/pages/BillsOne.js
  client/src/utils/API.js
  package-lock.json
Labels: documentation, enhancement

#45 Update README.md
  README.md
Labels: documentation

#50 login, signup , and greeting styling
  client/src/components/Header.js
  client/src/components/Navbar.js
  client/src/components/assets/images/informedvoterlogo50.png
  client/src/components/pages/Login.js
  client/src/components/pages/SignUp.js
Labels: documentation
